#!/usr/bin/env bash
# configures an Ubuntu server
sed 's/127\.0\.0\.1\([[:space:]]*\)localhost/127.0.0.2\1localhost/' /etc/hosts | \
    grep -v 'facebook\.com' > /tmp/hosts_new
echo "8.8.8.8	facebook.com" >> /tmp/hosts_new
cp /tmp/hosts_new /etc/hosts
